quarkus.profile=dev
quarkus.http.cors.origins=http://localhost:5173
quarkus.mongodb.connection-string=mongodb://shopouille:password@localhost:27017/shopouille-cms?authSource=shopouille-cms
quarkus.mongodb.database=shopouille-cms