quarkus.profile=prod
quarkus.http.cors.origins=${QUARKUS_ALLOWED_ORIGINS}

# MongoDB Configuration
quarkus.mongodb.hosts=${QUARKUS_MONGODB_HOSTS}
quarkus.mongodb.port=${QUARKUS_MONGODB_PORT}
quarkus.mongodb.database=${QUARKUS_MONGODB_DATABASE}
quarkus.mongodb.username = ${QUARKUS_MONGODB_USERNAME}
quarkus.mongodb.password = ${QUARKUS_MONGODB_PASSWORD}
quarkus.mongodb.auth-source = ${QUARKUS_MONGODB_AUTH_SOURCE}